version: "3.4"
services:
  backend:
    build:
      context: backend
    ports:
      - "3443:3443"
  couchbase:
    image: couchbase:community
    ports:
    - "8091-8094:8091-8094"
    - "11210:11210"
